name: CI
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  change-detection:
    name: 🔍 Change
    uses: cda-tum/mqt-workflows/.github/workflows/reusable-change-detection.yml@v1.4

  python-tests:
    name: 🐍 Test
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-python-tests)
    uses: cda-tum/mqt-workflows/.github/workflows/reusable-python-ci.yml@v1.4

  run-specific-test:
    name: 🐍 Run Specific Test with Secret
    needs: python-tests
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 3
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      IBM_TOKEN: ${{ secrets.IBM_TOKEN }}
    steps:
      # Check out the repository (including submodules and full history)
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # Set up uv for faster Python package management
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
          enable-cache: true

      # Set up nox for convenient testing
      - uses: wntrblm/nox@2024.10.09

      # Run the specific tests
      - name: 🐍 Run specific tests
        run: |
          nox -s tests -- \
            tests/devices/test_devices.py \
            tests/test_bench.py::test_quantumcircuit_native_and_mapped_levels \
            --cov --cov-report=xml:coverage-specific.xml --cov-append

      # Upload coverage report for this specific test
      - name: Upload 🐍 coverage report for specific test
        uses: actions/upload-artifact@v4
        with:
          name: coverage-specific
          path: coverage-specific.xml

  code-ql:
    name: 📝 CodeQL
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-code-ql)
    uses: cda-tum/mqt-workflows/.github/workflows/reusable-code-ql-python.yml@v1.4

  required-checks-pass: # This job does nothing and is only used for branch protection
    name: 🚦 Check
    if: always()
    needs:
      - change-detection
      - python-tests
      - code-ql
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: >-
            ${{
              fromJSON(needs.change-detection.outputs.run-python-tests)
              && '' || 'python-tests,'
            }}
            ${{
              fromJSON(needs.change-detection.outputs.run-code-ql)
              && '' || 'code-ql,'
            }}
          jobs: ${{ toJSON(needs) }}
